// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXPDguWV4ltjMOBEBE_ODJzC-xvjZ-_F8',
    appId: '1:840589975125:web:5fe8a6e8b77c7005c6fedc',
    messagingSenderId: '840589975125',
    projectId: 'whatsapp-b4c3e',
    authDomain: 'whatsapp-b4c3e.firebaseapp.com',
    storageBucket: 'whatsapp-b4c3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlIxgk8pbDdJuhM0IeefvaXKQSN3T-S8U',
    appId: '1:840589975125:android:798afd14a847646bc6fedc',
    messagingSenderId: '840589975125',
    projectId: 'whatsapp-b4c3e',
    storageBucket: 'whatsapp-b4c3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqeGzUWKNH8RULbjm8ejBW_u9I9jOnBtU',
    appId: '1:840589975125:ios:8925e57aeca578a1c6fedc',
    messagingSenderId: '840589975125',
    projectId: 'whatsapp-b4c3e',
    storageBucket: 'whatsapp-b4c3e.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqeGzUWKNH8RULbjm8ejBW_u9I9jOnBtU',
    appId: '1:840589975125:ios:8925e57aeca578a1c6fedc',
    messagingSenderId: '840589975125',
    projectId: 'whatsapp-b4c3e',
    storageBucket: 'whatsapp-b4c3e.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXPDguWV4ltjMOBEBE_ODJzC-xvjZ-_F8',
    appId: '1:840589975125:web:bae304e95b2a508dc6fedc',
    messagingSenderId: '840589975125',
    projectId: 'whatsapp-b4c3e',
    authDomain: 'whatsapp-b4c3e.firebaseapp.com',
    storageBucket: 'whatsapp-b4c3e.firebasestorage.app',
  );
}
